apiVersion: apps/v1
kind: Deployment
metadata:
  name: the-invincible-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: the-invincible-app
  template:
    metadata:
      labels:
        app: the-invincible-app
    spec:
      containers:
      - name: the-invincible-app
        image: registry.digitalocean.com/deploy2025/the-invincible-app:latest
        ports:
        - containerPort: 8080
        env:
        - name: REGION_LOCAL
          value: "New York"
        - name: REGION_REMOTE
          value: "Amsterdam"   
        - name: DB_USER
          value: "doadmin"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: db_password
        - name: DB_HOST_LOCAL
          value: "private-db-ro-postgresql-nyc1-do-user-0.k.db.ondigitalocean.com"
        - name: DB_HOST_REMOTE
          value: "private-db-postgresql-ams3-do-user-0.l.db.ondigitalocean.com"
        - name: DB_PORT
          value: "25060"
        - name: DB_NAME
          value: "defaultdb"
        - name: PORT
          value: "8080"
        - name: SVC_IP_REMOTE
          value: "10.110.16.6"
---
apiVersion: v1
kind: Service
metadata:
  name: the-invincible-app-service
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-network: "INTERNAL"
    service.beta.kubernetes.io/do-loadbalancer-size-unit: "2"
    service.beta.kubernetes.io/do-loadbalancer-override-health-check: "true"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-port: "80"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-protocol: "http"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-path: "/health"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-check-interval-seconds: "3"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-response-timeout-seconds: "3"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-unhealthy-threshold: "2"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-healthy-threshold: "2"
spec:
  selector:
    app: the-invincible-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
---
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  db_password: QVZOU19MRWtwUyVlJXYVNx